# To install the git pre-commit hooks run:
#   pre-commit install (--hook-type pre-push) (--hook-type post-checkout) (--hook-type pre-commit)
# To run pre-commit hooks manually on all files run:
#   pre-commit run --all-files
# To update all hooks to the latest version run:
#   pre-commit autoupdate

# More hook types can be added to be installed by default
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.9
    hooks:
      - id: uv-lock
      - id: uv-export
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10240]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: .pdf|.svg|.graphml
      - id: pretty-format-json
        exclude: .ipynb|.vscode/settings.json
        args: [--autofix]
      - id: mixed-line-ending
        exclude: .pdf|.svg|.graphml
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.14.5
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: [types-pytz, types-requests, types-PyYAML]
  - repo: https://github.com/crate-ci/typos.git
    rev: v1.39.2
    hooks:
      - id: typos
        args: [--force-exclude]
        exclude: .pdf|.svg|.graphml|.excalidraw
        # TODO: add false positives to _typos.toml to ignore (see instructions on https://github.com/crate-ci/typos)
